FROM openjdk:18
COPY target/audit-checklist-service-0.0.1-SNAPSHOT.jar audit-checklist-service-0.0.1-SNAPSHOT.jar
EXPOSE 8001
ENTRYPOINT ["java", "-jar", "/audit-checklist-service-0.0.1-SNAPSHOT.jar"]